def show_doc():
    print("This is PyCalc!")
    print("Available commands:")
    print("add -> sum two values; x [add] y")
    print("sub -> subtract two values; x [sub] y")
    print("multi -> multiply two values; x [multi] y")
    print("div -> divide two values; x [div] y")
    print("\n-odd or -even -> the program will accept just odd or even numbers.")
    print("-f: flag to float numbers.")
    print("\nExample: 10 add 60 div 2 add 2")
    print("42")